
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class VentanaAhorcado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
    }
    
    private void chequeaBoton(JButton boton){
        boton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display = new javax.swing.JLabel();
        VisorImagen = new javax.swing.JLabel();
        jButtonC = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonÑ = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonEspacio = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Display.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Display.setText("_ _ _ _ _");

        jButtonC.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCMousePressed(evt);
            }
        });

        jButtonA.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonA.setText("A");
        jButtonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAMousePressed(evt);
            }
        });

        jButtonB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonB.setText("B");
        jButtonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBMousePressed(evt);
            }
        });

        jButtonD.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonD.setText("D");
        jButtonD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDMousePressed(evt);
            }
        });

        jButtonE.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonE.setText("E");
        jButtonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEMousePressed(evt);
            }
        });
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonV.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonV.setText("V");
        jButtonV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonVMousePressed(evt);
            }
        });
        jButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVActionPerformed(evt);
            }
        });

        jButtonF.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonF.setText("F");
        jButtonF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonFMousePressed(evt);
            }
        });
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });

        jButtonH.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonH.setText("H");
        jButtonH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonHMousePressed(evt);
            }
        });

        jButtonI.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonI.setText("I");
        jButtonI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonIMousePressed(evt);
            }
        });

        jButtonJ.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonJ.setText("J");
        jButtonJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonJMousePressed(evt);
            }
        });

        jButtonK.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonK.setText("K");
        jButtonK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonKMousePressed(evt);
            }
        });

        jButtonL.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonL.setText("L");
        jButtonL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonLMousePressed(evt);
            }
        });

        jButtonM.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonM.setText("M");
        jButtonM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMMousePressed(evt);
            }
        });

        jButtonY.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonY.setText("Y");
        jButtonY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonYMousePressed(evt);
            }
        });
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });

        jButtonX.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonX.setText("X");
        jButtonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonXMousePressed(evt);
            }
        });
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });

        jButtonU.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonU.setText("U");
        jButtonU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonUMousePressed(evt);
            }
        });
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUActionPerformed(evt);
            }
        });

        jButtonZ.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonZ.setText("Z");
        jButtonZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonZMousePressed(evt);
            }
        });
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZActionPerformed(evt);
            }
        });

        jButtonN.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonN.setText("N");
        jButtonN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonNMousePressed(evt);
            }
        });
        jButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNActionPerformed(evt);
            }
        });

        jButtonÑ.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonÑ.setText("Ñ");
        jButtonÑ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonÑMousePressed(evt);
            }
        });

        jButtonO.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonO.setText("O");
        jButtonO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonOMousePressed(evt);
            }
        });

        jButtonP.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonP.setText("P");
        jButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPMousePressed(evt);
            }
        });

        jButtonQ.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonQ.setText("Q");
        jButtonQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonQMousePressed(evt);
            }
        });

        jButtonR.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonR.setText("R");
        jButtonR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonRMousePressed(evt);
            }
        });

        jButtonS.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonS.setText("S");
        jButtonS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSMousePressed(evt);
            }
        });

        jButtonT.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonT.setText("T");
        jButtonT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonTMousePressed(evt);
            }
        });
        jButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTActionPerformed(evt);
            }
        });

        jButtonG.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonG.setText("G");
        jButtonG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonGMousePressed(evt);
            }
        });
        jButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGActionPerformed(evt);
            }
        });

        jButtonEspacio.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonEspacio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEspacioMousePressed(evt);
            }
        });
        jButtonEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspacioActionPerformed(evt);
            }
        });

        jButtonW.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonW.setText("W");
        jButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonWMousePressed(evt);
            }
        });
        jButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(VisorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VisorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonCMousePressed

    private void jButtonAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonAMousePressed

    private void jButtonBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonBMousePressed

    private void jButtonDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonDMousePressed

    private void jButtonEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonEMousePressed

    private void jButtonVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonVMousePressed

    private void jButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonVActionPerformed

    private void jButtonFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonFMousePressed

    private void jButtonHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonHMousePressed

    private void jButtonIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonIMousePressed

    private void jButtonJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonJMousePressed

    private void jButtonKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonKMousePressed

    private void jButtonLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonLMousePressed

    private void jButtonMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonMMousePressed

    private void jButtonYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonYMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonYMousePressed

    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonYActionPerformed

    private void jButtonXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonXMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonXMousePressed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonUMousePressed

    private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonUActionPerformed

    private void jButtonZMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonZMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonZMousePressed

    private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonZActionPerformed

    private void jButtonNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonNMousePressed

    private void jButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonNActionPerformed

    private void jButtonÑMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonÑMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonÑMousePressed

    private void jButtonOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonOMousePressed

    private void jButtonPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonPMousePressed

    private void jButtonQMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonQMousePressed

    private void jButtonRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonRMousePressed

    private void jButtonSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonSMousePressed

    private void jButtonTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonTMousePressed

    private void jButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonTActionPerformed

    private void jButtonGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonGMousePressed

    private void jButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonGActionPerformed

    private void jButtonEspacioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEspacioMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonEspacioMousePressed

    private void jButtonEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspacioActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonEspacioActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonWMousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonWMousePressed

    private void jButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonWActionPerformed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_jButtonFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Display;
    private javax.swing.JLabel VisorImagen;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonEspacio;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JButton jButtonÑ;
    // End of variables declaration//GEN-END:variables
}
